tweaks again

diff --git a/.github/workflows/hygiene-dashboard.yaml b/.github/workflows/hygiene-dashboard.yaml
--- a/.github/workflows/hygiene-dashboard.yaml
+++ b/.github/workflows/hygiene-dashboard.yaml
@@ -167,11 +167,10 @@ jobs:
 
           # Write summary
           echo "### 🧪 Hygiene Summary (Checkstyle + PMD + JaCoCo)" >> $env:GITHUB_STEP_SUMMARY
-          echo "|               Metrics             |         Values       |" >> $env:GITHUB_STEP_SUMMARY
+          echo "|               **Metrics**         |         **Values**   |" >> $env:GITHUB_STEP_SUMMARY
           echo "|-----------------------------------|----------------------|" >> $env:GITHUB_STEP_SUMMARY
           echo "| Checkstyle Violations             | $checkstyleViolations|" >> $env:GITHUB_STEP_SUMMARY
           echo "| PMD Code Smells                   | $pmdViolations       |" >> $env:GITHUB_STEP_SUMMARY
-          echo "|-----------------------------------|----------------------|" >> $env:GITHUB_STEP_SUMMARY
           echo "| Total (PMD=CHECKSTYLE) Violations | $totalViolations     |" >> $env:GITHUB_STEP_SUMMARY
           echo "| Coverage                          | $jacocoCoverage%     |" >> $env:GITHUB_STEP_SUMMARY
           
@@ -180,7 +179,7 @@ jobs:
           } else {
             echo "**✅ Good Coverage Levels in code!** Great job! 🎉" >> $env:GITHUB_STEP_SUMMARY
           }
-
+        
           if ($totalViolations -eq 0) {
             echo "**✅ Clean Code!** Great job! 🎉" >> $env:GITHUB_STEP_SUMMARY
           } elseif ($totalViolations -lt $env:CHECKSTYLE_PMD_MAX_TOTAL_VIOLATIONS) {
@@ -207,7 +206,11 @@ jobs:
           # Outcome message
           if ($totalViolations -eq 0 -and -not $shouldFail) {
           echo "**✅ Clean Code!** Great job! 🎉" >> $env:GITHUB_STEP_SUMMARY
-          } 
+          } elseif ($shouldFail) {
+            echo "**❌ Failing due to threshold violations.**" >> $env:GITHUB_STEP_SUMMARY
+            exit 1
+          }
+
       ##########################
       # SUMMARY SECTION
       ##########################
